/* Generated By:JavaCC: Do not edit this line. MyNewGrammarTreeConstants.java Version 5.0 */
package sql;

public interface MyNewGrammarTreeConstants
{
  public int JJTSTART = 0;
  public int JJTSTATEMENT = 1;
  public int JJTEXIT = 2;
  public int JJTUSE = 3;
  public int JJTSHOW = 4;
  public int JJTTYPE = 5;
  public int JJTTABLE = 6;
  public int JJTTABLES = 7;
  public int JJTTABLE_COLUMN = 8;
  public int JJTCOLUMN = 9;
  public int JJTDB = 10;
  public int JJTP_KEY = 11;
  public int JJTCHECK = 12;
  public int JJTUNIQUE = 13;
  public int JJTCONSTRAINT = 14;
  public int JJTDEFINITION = 15;
  public int JJT_DEFINITION = 16;
  public int JJTVIEW = 17;
  public int JJTCREATE = 18;
  public int JJTSTAR_ALL = 19;
  public int JJTTARGET = 20;
  public int JJTTARGETFOLLOW = 21;
  public int JJTLEFTCOMP = 22;
  public int JJTRIGHTCOMP = 23;
  public int JJTOPERATOR = 24;
  public int JJTCONDITION = 25;
  public int JJTCONDITIONS = 26;
  public int JJTE = 27;
  public int JJT_E = 28;
  public int JJTT = 29;
  public int JJT_T = 30;
  public int JJTF = 31;
  public int JJTSELECT = 32;
  public int JJTDROP = 33;
  public int JJTDROPTARGET = 34;
  public int JJTINSERT = 35;
  public int JJTA = 36;
  public int JJTC = 37;
  public int JJTB = 38;
  public int JJTSTRING = 39;
  public int JJTNUM = 40;
  public int JJTBOOL = 41;
  public int JJTVALUE = 42;
  public int JJTKEY_VALUE = 43;
  public int JJTDELETE = 44;
  public int JJTDELETEFOLLOW = 45;
  public int JJTUPDATE = 46;


  public String[] jjtNodeName = {
    "Start",
    "Statement",
    "Exit",
    "Use",
    "Show",
    "Type",
    "Table",
    "Tables",
    "Table_Column",
    "Column",
    "DB",
    "P_Key",
    "Check",
    "Unique",
    "Constraint",
    "Definition",
    "_Definition",
    "View",
    "Create",
    "Star_All",
    "Target",
    "TargetFollow",
    "leftComp",
    "rightComp",
    "operator",
    "Condition",
    "Conditions",
    "E",
    "_E",
    "T",
    "_T",
    "F",
    "Select",
    "Drop",
    "DropTarget",
    "Insert",
    "A",
    "C",
    "B",
    "String",
    "Num",
    "Bool",
    "Value",
    "KEY_VALUE",
    "Delete",
    "DeleteFollow",
    "Update",
  };
}
/* JavaCC - OriginalChecksum=a42dc79b9ce7b587a25e260c6b00a1f3 (do not edit this line) */
