/* Generated By:JJTree&JavaCC: Do not edit this line. MyNewGrammarConstants.java */
package sql;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MyNewGrammarConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int P_KEY = 5;
  /** RegularExpression Id. */
  int UNIQUE = 6;
  /** RegularExpression Id. */
  int CHECK = 7;
  /** RegularExpression Id. */
  int USE = 8;
  /** RegularExpression Id. */
  int SHOW = 9;
  /** RegularExpression Id. */
  int SELECT = 10;
  /** RegularExpression Id. */
  int DROP = 11;
  /** RegularExpression Id. */
  int EXIT = 12;
  /** RegularExpression Id. */
  int FROM = 13;
  /** RegularExpression Id. */
  int WHERE = 14;
  /** RegularExpression Id. */
  int CREATE = 15;
  /** RegularExpression Id. */
  int INSERT = 16;
  /** RegularExpression Id. */
  int INTO = 17;
  /** RegularExpression Id. */
  int DELETE = 18;
  /** RegularExpression Id. */
  int UPDATE = 19;
  /** RegularExpression Id. */
  int SET = 20;
  /** RegularExpression Id. */
  int AND = 21;
  /** RegularExpression Id. */
  int OR = 22;
  /** RegularExpression Id. */
  int AS = 23;
  /** RegularExpression Id. */
  int KW_TABLE = 24;
  /** RegularExpression Id. */
  int KW_DATABASE = 25;
  /** RegularExpression Id. */
  int KW_VIEW = 26;
  /** RegularExpression Id. */
  int STAR = 27;
  /** RegularExpression Id. */
  int VALUES = 28;
  /** RegularExpression Id. */
  int KW_BOOL = 29;
  /** RegularExpression Id. */
  int KW_STR = 30;
  /** RegularExpression Id. */
  int KW_INT = 31;
  /** RegularExpression Id. */
  int NUM = 32;
  /** RegularExpression Id. */
  int STR = 33;
  /** RegularExpression Id. */
  int BOOL = 34;
  /** RegularExpression Id. */
  int ID = 35;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"PRIMARY KEY\"",
    "\"UNIQUE\"",
    "\"CHECK\"",
    "\"USE\"",
    "\"SHOW\"",
    "\"SELECT\"",
    "\"DROP\"",
    "\"EXIT\"",
    "\"FROM\"",
    "\"WHERE\"",
    "\"CREATE\"",
    "\"INSERT\"",
    "\"INTO\"",
    "\"DELETE\"",
    "\"UPDATE\"",
    "\"SET\"",
    "<AND>",
    "<OR>",
    "\"AS\"",
    "\"TABLE\"",
    "\"DATABASE\"",
    "\"VIEW\"",
    "\"*\"",
    "\"values\"",
    "\"BOOL\"",
    "\"STRING\"",
    "\"INT\"",
    "<NUM>",
    "<STR>",
    "<BOOL>",
    "<ID>",
    "\";\"",
    "\",\"",
    "\".\"",
    "\"(\"",
    "\")\"",
    "\"<\"",
    "\">\"",
    "\">=\"",
    "\"<=\"",
    "\"==\"",
    "\"!=\"",
  };

}
